services:
  redis:
    image: redis:6.2.6
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight:latest
    ports:
      - "5540:5540"
    depends_on:
      - redis

  redis-insight-config:
    image: alcyondev/redis-insight-config:latest
    environment:
      RI_ACCEPT_EULA: true
    depends_on:
      - redis
      - redis-insight
